### ISSUE TITLE
compiling on Ubuntu 16.04

### ISSUE THREAD

**Issue by lulu1315** [YinlinHu/Ric#3]
hello . thank you for the code!
I'm trying to compile on Ubuntu 16.04 (KDE Neon) and I'm getting these errors 
(using OpenCV 3.4.0) I compiled CPM with no problems
any help would be welcomed
luc

> 

make
Scanning dependencies of target CPM
[ 25%] Building CXX object CMakeFiles/CPM.dir/main.cpp.o
In file included from /shared/foss/Ric/./include/Image.h:15:0,
                 from /shared/foss/Ric/RIC.h:4,
                 from /shared/foss/Ric/main.cpp:1:
/shared/foss/Ric/./include/ImageIO.h: In instantiation of ‘static void ImageIO::showGrayImageAsColor(const char*, const unsigned char*, int, int, T, T, int) [with T = int]’:
/shared/foss/Ric/./include/Image.h:1008:32:   required from ‘void Image<T>::imagesc(char*, int) const [with T = float]’
/shared/foss/Ric/main.cpp:106:1:   required from here
/shared/foss/Ric/./include/ImageIO.h:124:10: warning: format ‘%f’ expects argument of type ‘double’, but argument 3 has type ‘int’ [-Wformat=]
   sprintf(info, "[%.3f, %.3f]", minV, maxV);
          ^
/shared/foss/Ric/./include/ImageIO.h:124:10: warning: format ‘%f’ expects argument of type ‘double’, but argument 4 has type ‘int’ [-Wformat=]
[ 50%] Building CXX object CMakeFiles/CPM.dir/RIC.cpp.o
In file included from /shared/foss/Ric/./include/Image.h:7:0,
                 from /shared/foss/Ric/RIC.h:4,
                 from /shared/foss/Ric/RIC.cpp:1:
/shared/foss/Ric/./include/ImageProcessing.h: In instantiation of ‘static void ImageProcessing::Medianfiltering(const T1*, T2*, int, int, int, int) [with T1 = float; T2 = float]’:
/shared/foss/Ric/./include/Image.h:1380:34:   required from ‘void Image<T>::MedianFiltering(int) [with T = float]’
/shared/foss/Ric/RIC.cpp:244:21:   required from here
/shared/foss/Ric/./include/ImageProcessing.h:456:9: error: ‘sort’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
     sort(pTmpSrc, pTmpSrc + regionSize);
         ^
In file included from /usr/include/c++/5/algorithm:62:0,
                 from /opt/opencv-3.4.0/include/opencv2/core/base.hpp:55,
                 from /opt/opencv-3.4.0/include/opencv2/core.hpp:54,
                 from /opt/opencv-3.4.0/include/opencv2/opencv.hpp:52,
                 from /shared/foss/Ric/./include/ImageIO.h:7,
                 from /shared/foss/Ric/./include/Image.h:15,
                 from /shared/foss/Ric/RIC.h:4,
                 from /shared/foss/Ric/RIC.cpp:1:
/usr/include/c++/5/bits/stl_algo.h:4718:5: note: ‘template<class _RAIter, class _Compare> void std::sort(_RAIter, _RAIter, _Compare)’ declared here, later in the translation unit
     sort(_RandomAccessIterator __first, _RandomAccessIterator __last,
     ^
In file included from /shared/foss/Ric/./include/Image.h:15:0,
                 from /shared/foss/Ric/RIC.h:4,
                 from /shared/foss/Ric/RIC.cpp:1:
/shared/foss/Ric/./include/ImageIO.h: In instantiation of ‘static void ImageIO::showGrayImageAsColor(const char*, const unsigned char*, int, int, T, T, int) [with T = int]’:
/shared/foss/Ric/./include/Image.h:1008:32:   required from ‘void Image<T>::imagesc(char*, int) const [with T = int]’
/shared/foss/Ric/RIC.cpp:951:1:   required from here
/shared/foss/Ric/./include/ImageIO.h:124:10: warning: format ‘%f’ expects argument of type ‘double’, but argument 3 has type ‘int’ [-Wformat=]
   sprintf(info, "[%.3f, %.3f]", minV, maxV);
          ^
/shared/foss/Ric/./include/ImageIO.h:124:10: warning: format ‘%f’ expects argument of type ‘double’, but argument 4 has type ‘int’ [-Wformat=]
CMakeFiles/CPM.dir/build.make:86: recipe for target 'CMakeFiles/CPM.dir/RIC.cpp.o' failed
make[2]: *** [CMakeFiles/CPM.dir/RIC.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/CPM.dir/all' failed
make[1]: *** [CMakeFiles/CPM.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

>

**Comment by YinlinHu** [comment]
It can now compiled on Linux
